# Set global configuration.
export EDITOR="vim"
PATH="$HOME/bin:$HOME/opt/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
PATH="$PATH:/usr/local/opt/python@3.7/bin"
PATH="$PATH:/usr/local/opt/python@3.8/bin"
PATH="$PATH:/usr/local/opt/python@3.9/bin"
PATH="$PATH:/usr/local/opt/python@3.10/bin"
export PATH="$PATH"
export LD_LIBRARY_PATH="$HOME/opt/lib:$LD_LIBRARY_PATH"
export MANPATH="$HOME/opt/share/man:$MANPATH"
export TERM="xterm-256color"
export ZSH=~/.oh-my-zsh
export PIP_REQUIRE_VIRTUALENV=true

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS=true

# Use hyphen-insensitive completion. _ and - will be interchangeable.
HYPHEN_INSENSITIVE=true

# Do not throw any error if a pattern for filename generation has no matches.
unsetopt NOMATCH

# Set theme and configure prompt segments.
ZSH_THEME="bullet-train"
BULLETTRAIN_PROMPT_ORDER=(
  time
  status
  custom
  dir
  perl
  ruby
  virtualenv
  go
  elixir
  git
  hg
  cmd_exec_time
)
BULLETTRAIN_TIME_BG=241
BULLETTRAIN_TIME_FG=254

# Set plugins to load.
plugins=(
  common-aliases  # aliases for many commonly used commands
  copyfile  # copy file contents to system clipboard
  copypath  # copy path of given file or directory to system clipboard
  docker  # autocompletion for docker
  emoji  # emojis using human-readable identifiers
  macos  # access to a few macOS applications from terminal
  pip  # autocompletion for pip
  python  # useful python aliases (e.g. pyfind, pyclean, pygrep)
  sudo  # prefix current/previous commands with sudo by pressing ESC twice
)

# Disable `url-quote-magic`.
DISABLE_MAGIC_FUNCTIONS=true

# Load `oh-my-zsh`.
source "$ZSH/oh-my-zsh.sh"

# Load `google-cloud-sdk`.
if [[ -f "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ]] ; then
  source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
fi
if [[ -f "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ]] ; then
  source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
fi

# Map various keys to custom functionality.
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
zmodload zsh/terminfo
bindkey "$terminfo[kent]" accept-line  # keypad Enter
bindkey "$terminfo[kcuu1]" history-beginning-search-backward-end  # Up arrow
bindkey "$terminfo[kcud1]" history-beginning-search-forward-end  # Down arrow
bindkey "^[[1~" beginning-of-line  # Fn + Left arrow
bindkey "^[[4~" end-of-line  # Fn + Right arrow

# Set colors for the GNU ls utility and for zsh completion.
case "$OSTYPE" in
  darwin*)
    eval `gdircolors ~/.dircolors`
    alias ls="gls -F --color=auto"
    ;;
  linux*)
    eval `dircolors ~/.dircolors`
    alias ls="ls -F --color=auto"
    ;;
esac
zstyle ":completion:*" list-colors ${(s.:.)LS_COLORS}

# Define additional aliases and functions.

alias ds="cd ~/datastore"
alias ws="cd ~/workspace"

function activate() {
  if [[ $# -ge 2 ]] ; then
    echo "Too many arguments! Usage: activate [env_dir]"
    return 1
  fi

  env_dir=".env"
  if [[ $# -ge 1 ]] ; then
    env_dir="$1"
  fi

  source "$env_dir/bin/activate"
}

function mkenv() {
  if [[ $# -gt 2 ]] ; then
    echo "Too many arguments! Usage: mkenv [env_dir python_bin]"
    return 1
  fi

  python_bin="python3"
  if [[ $# -ge 2 ]] ; then
    python_bin="$2"
  fi

  env_dir=".env"
  if [[ $# -ge 1 ]] ; then
    env_dir="$1"
  fi

  "$python_bin" -m venv "$env_dir"
  source "$env_dir/bin/activate"
  pip install --upgrade pip wheel
}

alias yt="yt720"
alias yto="yt-dlp"
alias yt720="yt-dlp -f 'bestvideo[height<=720]+bestaudio'"
alias yt1080="yt-dlp -f 'bestvideo[height<=1080]+bestaudio'"

# Enable local settings, which override general settings.
if [[ -f ~/.zshrc.local ]] ; then
  source ~/.zshrc.local
fi

# Attach to an existing tmux session or start a new one.
# TODO(stefanistrate): Fix VS Code startup issues caused by tmux, as described
# at https://github.com/microsoft/vscode/issues/173438.
if [[ "$TERM_PROGRAM" != "vscode" ]] ; then
  if which tmux &>/dev/null ; then
    if [[ -z $TMUX ]] ; then
      tmux has &>/dev/null
      if [[ $? -eq 1 ]] ; then
        exec tmux new
      else
        exec tmux attach
      fi
    fi
  fi
fi

# >>> conda initialize >>>
# !!! Contents within this block are managed by `conda init` !!!
__conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [[ $? -eq 0 ]] ; then
    eval "$__conda_setup"
else
    if [[ -f "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]] ; then
        source "/usr/local/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
